repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "."]


#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.28.1
#    hooks:
#      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      # - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.42.0
    hooks:
      - id: golangci-lint
        args: [--timeout=3m]
